= SQL tutorial

== Preparation

* install docker → https://www.docker.com/[https://www.docker.com/] → Get Docker → For Desktops
* `docker run -d --name postgres -p 5432:5432 postgres:alpine`
* `echo 'create database sen;' | docker run -i --rm --link postgres:postgres postgres:alpine psql -h postgres -U postgres postgres`
* `docker run -i --rm --link postgres:postgres postgres:alpine psql -h postgres -U postgres sen &lt; world/world.sql`

Stop and start without losing data:

* `docker stop postgres`
* `docker start postgres`

== Checklist

everybody…

- got docker installed
- got postgresql set up
- got database tool configured and could execute the sample query
- has a Java IDE
- has opened the progress spreadsheet

== Exercises

=== SQL

* open the PostgreSQL documentation at https://www.postgresql.org/docs/9.6/static/index.html[https://www.postgresql.org/docs/9.6/static/index.html] and use it as needed
* The database contains some outdated world data about cities, countries, and languages.

Try to solve every task twice.
Use whatever you need e.g. views, temporarily tables to get is solved during the first try.
After that try to solve it again with exactly 1 but possibly complex statement without using views or temporary tables.

Tasks:

. Become familar with the 3 database tables. Execute some simple queries to understand the data.

. Check for each country if the language percentages add up to 100%. The result should look like:
+
[%autowidth,cols="<,>",options="header"]
|===
^|countrycode
^|sum

|BLZ|98.8
|BGD|98.69999
|ITA|99.59998
|===

. Calculate the rounded number of speakers of each language in each country. Sample output:
+
[%autowidth,cols="<,>,<",options="header"]
|===
^|name
^|speakers
^|language

|Afghanistan|11905280|Pashto
|Netherlands|15165984|Dutch
|Netherlands Antilles|187054|Papiamento
|===

. Calculate the rounded number of speakers of each language in the world. Sort them by speakers descending.
+
[%autowidth,cols=">,<",options="header"]
|===
^|speakers
^|language

|1191843539|Chinese
|405633085|Hindi
|355029462|Spanish
|===

. Calculate the world population.
+
[%autowidth,cols="<",options="header"]
|===
^|sum

|6078749450
|===

. List all country names that have no official languages.
+
[%autowidth,cols="<",options="header"]
|===
^|name

|Aruba
|Afghanistan
|Angola
|===

. Calculate world population, average, max and median population of all countries, europe's population, population of all countries below median.
+
[%autowidth,cols="<,<,<,<,<,<",options="header"]
|===
^|sum|average|max|median|europe|belowmedian

|6078749450|25434098|1277558000|3869000|730074600|101437250
|===

. Calculate number of cities per country, sort by city count descending.
+
[%autowidth,cols="<,>",options="header"]
|===
^|name|citycount

|China|363
|India|341
|United States|274
|===

. Convert the first 10 countries to a JSON array of country objects.
+
[%autowidth,cols="<",options="header"]
|===
^|json

|[{"code":"AFG","name":"Afghanistan"...}, ..., {"code":"ATG","name":"Antigua and Barbuda",...}]
|===

. Aggregate first 2 countries to JSON where each country has 2 fields: country name and languages which is an array of JSON objects.
+
[%autowidth,cols="<",options="header"]
|===
^|json

|[{"name":"Afghanistan","languages":[{"countrycode":"AFG","language":"Pashto",...},{"countrycode":"AFG","language":"Dari",...},...]},...]
|===

. Calculate the percentage of each language in the world, format percentage like 0.123456, sort by percentage descending.
+
[%autowidth,cols=">,<",options="header"]
|===
^|percentage
^|language

|0.196067|Chinese
|0.066730|Hindi
|0.058405|Spanish
|===

. Same task as above with an additional rank column.
+
[%autowidth,cols=">,>,<",options="header"]
|===
^|rank
^|percentage
^|language

|1|0.196067|Chinese
|2|0.066730|Hindi
|3|0.058405|Spanish
|===

. Sort countries by population descending and add a rank column.
+
[%autowidth,cols="<,<,>,>",options="header"]
|===
^|code
^|name
^|rank
^|population

|CHN|China|1|1277558000
|IND|India|2|1013662000
|USA|United States|3|278357000
|===

. Calculate rank of language in each country sorted by percentage descending.
+
[%autowidth,cols="<,<,>,>",options="header"]
|===
^|code
^|language
^|rank
^|percentage

|ABW|Papiamento|1|76.7
|ABW|English|2|9.5
|ABW|Spanish|3|7.4
|ABW|Dutch|4|5.3
|AFG|Pashto|1|52.4
|AFG|Dari|2|32.1
|===

. Combine the tasks above. Sort countries by population descending first and language rank descending second.
+
[%autowidth,cols="<,>,>,<,>,>",options="header"]
|===
^|name
^|poprank
^|population
^|language
^|langrank
^|percentage

|China|1|1277558000|Chinese|1|92
|China|1|1277558000|Zhuang|2|1.4
|China|1|1277558000|Mantu|3|0.9
|China|1|1277558000|Hui|4|0.8
|China|1|1277558000|Miao|5|0.7
|China|1|1277558000|Uighur|6|0.6
|China|1|1277558000|Yi|7|0.6
|China|1|1277558000|Tujia|8|0.5
|China|1|1277558000|Tibetan|9|0.4
|China|1|1277558000|Mongolian|10|0.4
|China|1|1277558000|Puyi|11|0.2
|China|1|1277558000|Dong|12|0.2
|India|2|1013662000|Hindi|1|39.9
|India|2|1013662000|Bengali|2|8.2
|===

=== Java

The same tasks as in the SQL part should be solved with Java code.

You can read the full content of each table with the methods from interface WorldRepository.
The junit test RepositoryTest shows how to do that.
Please write your solution as junit tests as well.
But feel free to implement additional helper classes.

As in the sql part every task should be solved twice.
Try to find any correct solution first and feel free to use imperative code, explicit loops, and whatever you need to get it done.
Try to find a better, more functional solution using the Java 8 streams API in the 2nd step.
Cheat sheet: https://zeroturnaround.com/rebellabs/java-8-streams-cheat-sheet/

1. In the first task you should become familar with the java exercise.
 Execute the RepositoryTest.
 Start with writing a unit test that reads one table, implements some filtering and/or pagination, and outputs the results.

All the other tasks are the same as in the sql exercise.
Please use the methods from WorldRepository to fetch data from the database.
Do not modify or extend the sql queries any more because this is the java exercise.
